//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaionReminder.Properties {
	
	
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ICSharpCode.SettingsEditor.SettingsCodeGeneratorTool", "4.2.2.8818")]
	internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
		
		private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
		
		public static Settings Default {
			get {
				return defaultInstance;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool AutoExcludeCanceledCivil {
			get {
				return ((bool)(this["AutoExcludeCanceledCivil"]));
			}
			set {
				this["AutoExcludeCanceledCivil"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("GAS")]
		public string bsrBase {
			get {
				return ((string)(this["bsrBase"]));
			}
			set {
				this["bsrBase"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string bsrPass {
			get {
				return ((string)(this["bsrPass"]));
			}
			set {
				this["bsrPass"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.254:8079/")]
		public string BSRURL {
			get {
				return ((string)(this["BSRURL"]));
			}
			set {
				this["BSRURL"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("BSR")]
		public string bsrUser {
			get {
				return ((string)(this["bsrUser"]));
			}
			set {
				this["bsrUser"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool ExcludeInBSR {
			get {
				return ((bool)(this["ExcludeInBSR"]));
			}
			set {
				this["ExcludeInBSR"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool AddManualBSRExclusions {
			get {
				return ((bool)(this["AddManualBSRExclusions"]));
			}
			set {
				this["AddManualBSRExclusions"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool DenyOnlyInBSR {
			get {
				return ((bool)(this["DenyOnlyInBSR"]));
			}
			set {
				this["DenyOnlyInBSR"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("!#EXCLBASE#!")]
		public string exclBase {
			get {
				return ((string)(this["exclBase"]));
			}
			set {
				this["exclBase"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("!#EXCLPASS#!")]
		public string exclPass {
			get {
				return ((string)(this["exclPass"]));
			}
			set {
				this["exclPass"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("!#EXCLUSER#!")]
		public string exclUser {
			get {
				return ((string)(this["exclUser"]));
			}
			set {
				this["exclUser"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool FirstAdmAfterConsideration {
			get {
				return ((bool)(this["FirstAdmAfterConsideration"]));
			}
			set {
				this["FirstAdmAfterConsideration"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool FirstGrAfterConsideration {
			get {
				return ((bool)(this["FirstGrAfterConsideration"]));
			}
			set {
				this["FirstGrAfterConsideration"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool FirstLaunch {
			get {
				return ((bool)(this["FirstLaunch"]));
			}
			set {
				this["FirstLaunch"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public global::System.Collections.ObjectModel.ObservableCollection<JudgeGroup> JudgeGroups {
			get {
				return ((global::System.Collections.ObjectModel.ObservableCollection<JudgeGroup>)(this["JudgeGroups"]));
			}
			set {
				this["JudgeGroups"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool LaunchMinimized {
			get {
				return ((bool)(this["LaunchMinimized"]));
			}
			set {
				this["LaunchMinimized"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("-1")]
		public double MainWindowHeight {
			get {
				return ((double)(this["MainWindowHeight"]));
			}
			set {
				this["MainWindowHeight"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("-1")]
		public double MainWindowWidth {
			get {
				return ((double)(this["MainWindowWidth"]));
			}
			set {
				this["MainWindowWidth"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("-1")]
		public double MainWindowX {
			get {
				return ((double)(this["MainWindowX"]));
			}
			set {
				this["MainWindowX"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("-1")]
		public double MainWindowY {
			get {
				return ((double)(this["MainWindowY"]));
			}
			set {
				this["MainWindowY"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("30")]
		public int pub_days {
			get {
				return ((int)(this["pub_days"]));
			}
			set {
				this["pub_days"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("180")]
		public int scan_days {
			get {
				return ((int)(this["scan_days"]));
			}
			set {
				this["scan_days"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("192.168.0.254:C:\\DATA\\JUSTICE\\UNI_WORK2003.GDB")]
		public string sdpBase {
			get {
				return ((string)(this["sdpBase"]));
			}
			set {
				this["sdpBase"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string sdpPass {
			get {
				return ((string)(this["sdpPass"]));
			}
			set {
				this["sdpPass"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("SYSDBA")]
		public string sdpUser {
			get {
				return ((string)(this["sdpUser"]));
			}
			set {
				this["sdpUser"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool ShowCanceledCivil {
			get {
				return ((bool)(this["ShowCanceledCivil"]));
			}
			set {
				this["ShowCanceledCivil"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool ShowDaysAfterConsideration {
			get {
				return ((bool)(this["ShowDaysAfterConsideration"]));
			}
			set {
				this["ShowDaysAfterConsideration"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool useLocalSettings {
			get {
				return ((bool)(this["useLocalSettings"]));
			}
			set {
				this["useLocalSettings"] = value;
			}
		}
	}
}
